"""Installs the `marimo-team/marimo-pair` agent skill via the `skills`
CLI, run through `uvx deno` rather than requiring `npx`/Node as a
separate toolchain (caddie already depends on `uv`).

`.claude/skills/marimo-pair` is generated by this command, not vendored
in caddie's own git history (see `.gitignore`) — `caddie install`/
`caddie update` are what keep it present and current on a given
machine.
"""

import subprocess
from pathlib import Path

_SKILLS_INVOCATION = ["uvx", "deno", "-A", "npm:skills"]


def install_marimo_pair_skill(caddie_root: Path) -> None:
    """Add the skill if it isn't already present; a no-op otherwise."""
    if (caddie_root / ".claude" / "skills" / "marimo-pair").is_dir():
        return
    subprocess.run(
        [*_SKILLS_INVOCATION, "add", "marimo-team/marimo-pair"],
        cwd=caddie_root,
        check=True,
    )


def upgrade_marimo_pair_skill(caddie_root: Path) -> None:
    """Pull the latest version of the skill, installing it if missing."""
    if not (caddie_root / ".claude" / "skills" / "marimo-pair").is_dir():
        install_marimo_pair_skill(caddie_root)
        return
    subprocess.run(
        [*_SKILLS_INVOCATION, "upgrade", "marimo-team/marimo-pair"],
        cwd=caddie_root,
        check=True,
    )
