"""Installs the `marimo-team/marimo-pair` agent skill via the `skills`
CLI, run through `uvx deno` rather than requiring `npx`/Node as a
separate toolchain (caddie already depends on `uv`).

`.claude/skills/marimo-pair` is generated by this command, not vendored
in caddie's own git history (see `.gitignore`) — `caddie install`/
`caddie update` are what keep it present and current on a given
machine.
"""

import subprocess
from pathlib import Path

_SKILLS_INVOCATION = ["uvx", "deno", "-A", "npm:skills"]


def install_marimo_pair_skill(caddie_root: Path) -> None:
    """Add the skill if it isn't already present; a no-op otherwise."""
    if (caddie_root / ".claude" / "skills" / "marimo-pair").is_dir():
        return
    subprocess.run(
        [*_SKILLS_INVOCATION, "add", "marimo-team/marimo-pair"],
        cwd=caddie_root,
        check=True,
    )


def upgrade_marimo_pair_skill(caddie_root: Path) -> None:
    """Pull the latest version of the skill, installing it if missing.

    `update`/`upgrade` (aliases of the same subcommand) take installed
    *skill names* (`marimo-pair`, `retro-marimo-pair`, as `skills list`
    shows them), not a source spec like `marimo-team/marimo-pair` — the
    latter silently matches nothing (`No installed skills found
    matching: ...`, exit 0). `-p -y` scopes to project skills and
    skips the confirmation prompt without naming skills explicitly, so
    any other skill later bundled from this same source is covered
    too, while the unrelated local `caddie-*` skills are left alone.
    """
    if not (caddie_root / ".claude" / "skills" / "marimo-pair").is_dir():
        install_marimo_pair_skill(caddie_root)
        return
    subprocess.run(
        [*_SKILLS_INVOCATION, "update", "-p", "-y"],
        cwd=caddie_root,
        check=True,
    )
